In [1]:
import numpy as np

In [18]:
a=np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [7]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.dtype

dtype('int64')

In [19]:
a.itemsize

1

Get size

In [12]:
a.size

3

Get total size

In [20]:
a.size * a.itemsize

3

In [21]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

Get a specific element

In [22]:
a[1,5]

13

In [23]:
# get specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# get specific column
a[:,2]

array([ 3, 10])

In [27]:
a[0,1:-1:2]

array([2, 4, 6])

In [28]:
#replace the value
a[1,5]=20

In [30]:
a[1]

array([ 8,  9, 10, 11, 12, 20, 14])

In [31]:
#replace value to colum
a[:,2]=[1,2]

In [32]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [ ]:
#3 D Example

In [77]:
c=np.array([[[1,2],
             [3,4]],
            [[5,6],
             [7,8]],
            [[9,10],
             [11,12]],
            [[13,14],
             [15,16]]])

In [38]:
c[3][1][1]

16

In [39]:
c[3,:,:]

array([[13, 14],
       [15, 16]])

In [41]:
c[1,:,1]

array([6, 8])

In [43]:
c[2,:,0]

array([ 9, 11])

In [44]:
c[0,1,0]

3

In [46]:
c[2,0,1]

10

In [65]:
d=np.array([[[1,2],
             [3,4]],
            [[5,6],
             [7,8]]])


d[:,1,:]=[[7,7],
          [9,9]]

In [81]:
c[:,1,:]=[[7,7],[9,9],[10,10],[11,11]]

In [82]:
c

array([[[ 1,  2],
        [ 7,  7]],

       [[ 5,  6],
        [ 9,  9]],

       [[ 9, 10],
        [10, 10]],

       [[13, 14],
        [11, 11]]])

In [84]:
c[:,1,:]

array([[ 7,  7],
       [ 9,  9],
       [10, 10],
       [11, 11]])

In [87]:
#All Zeros

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [90]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [91]:
#any other number

np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [92]:
#any other number (full_like)

np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [94]:
np.random.rand(4,2,3)

array([[[0.89580438, 0.75847618, 0.49073644],
        [0.28744489, 0.11853019, 0.21640715]],

       [[0.26432303, 0.81715496, 0.19254835],
        [0.70139963, 0.7616657 , 0.73184451]],

       [[0.93502545, 0.28555204, 0.60697432],
        [0.77673024, 0.83690477, 0.30702138]],

       [[0.38210409, 0.44464389, 0.08949731],
        [0.63372894, 0.58679344, 0.4861793 ]]])

In [95]:
np.random.random_sample(a.shape)

array([[0.47984598, 0.67829237, 0.41511241, 0.89031949, 0.70624574,
        0.36211519, 0.23260916],
       [0.77568252, 0.60853923, 0.34785594, 0.29831179, 0.15569069,
        0.4440383 , 0.13640564]])

In [96]:
np.random.randint(7, size=(3,3))

array([[0, 1, 5],
       [4, 0, 2],
       [3, 4, 6]])

In [99]:
np.random.randint(-3,8,size=(3,3))

array([[ 7,  7,  7],
       [ 4,  5, -2],
       [-3,  7, -2]])

In [100]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
#Repeat Array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [118]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=1
z
output[2:5,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.]])